### ISSUE TITLE
Python3 TypeError: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by ryanhz** [bowdentheo/BLE-Beacon-Scanner#2]
File "BeaconScanner.py", line 19, in <module>
    returnedList = ScanUtility.parse_events(sock, 10)
  File "/home/pi/BLE-Beacon-Scanner/ScanUtility.py", line 107, in parse_events
    rssi, = struct.unpack("b", packet[packetOffset -1])
TypeError: a bytes-like object is required, not 'int'

**Comment by ccloquet** [comment]
(The same happens also at line 72)

**Comment by sannzay** [comment]
This is acceptable only in Python 2. If you are running it in Python 3, use bytes().  
Eg: struct.unpack("b", bytes(packet[packetOffset -1]))
